repo_url: https://github.com/Requisitos-de-Software/2025.1-Carteira-Digital-de-Transito
repo_name: 2025.1-Carteira-Digital-de-Transito

site_name: Carteira Digital de Trânsito

nav:
  - Home: index.md
  - Apresentação: apresentacoes/apresentacao.md
  - Atas:
    - Ata 1: atas/ata01.md
    - Ata 2: atas/ata02.md
    - Ata 3: atas/ata03.md
  - Pré-Rastreabilidade: 
    - Rich Picture: pre-rastreabilidade/rich_picture.md
  - Planejamento:
    - Aplicativos Selecionados: planejamento/aplicativos_selecionados.md
    - Aplicativo Escolhido: planejamento/app_selecionado.md
    - Ferramentas: planejamento/ferramentas.md
    - Heat Map: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
    - Metodologia: planejamento/metodologia.md
    - Termo de Uso: planejamento/termos_de_uso.md
  - Verificação:
     - Grupo:
        - Entrega 1:
              - Verificação Grupo 9: verificacao/grupo/entrega01/planejamento-verificacao.md
              - Verificação Próprio Grupo: verificacao/grupo/entrega01/inspecao.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Claro

  language: pt-BR
  favicon: assets/image.png
  logo: assets/image.png
